name: Test Build

on:
  pull_request:
    branches:
      - main
      - master
  push:
    branches:
      - main
      - master
    paths:
      - 'Dockerfile'
      - 'compose.yaml'
      - '.github/workflows/**'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  test-build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64

      - name: Extract metadata for test
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=raw,value=test

      - name: Test build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            BUILDKIT_INLINE_CACHE=1

      - name: Test compose configuration
        run: |
          # .env.exampleを.envにコピーしてテスト
          cp .env.example .env
          # compose.yamlの構文チェック
          docker compose config --quiet
          echo "✅ Docker Compose configuration is valid"

      - name: Run basic container test
        run: |
          # テスト用にローカルイメージをビルド
          docker build -t test-glusterfs:latest .
          
          # 基本的なコンテナ起動テスト
          docker run --name test-container -d --privileged \
            -v /sys/fs/cgroup:/sys/fs/cgroup:ro \
            test-glusterfs:latest
          
          # コンテナが正常に起動したかチェック
          sleep 10
          docker ps | grep test-container
          
          # GlusterFSサービスの状態確認
          docker exec test-container systemctl is-active glusterd || true
          
          # クリーンアップ
          docker stop test-container
          docker rm test-container
          docker rmi test-glusterfs:latest
          
          echo "✅ Basic container functionality test passed"
